#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#PC01- Graffitti
#Howard,Bandoni
#DATE(20200128)
#
#This code is designed to make graffitti on the screeen
#========

from turtle import *

money = Screen()

money.screensize(400,600)
money.update()

money.bgcolor('white')
money.bgpic("gradient1.gif")

money.update()

taylor = Turtle()
taylor.hideturtle()
taylor.pencolor("white")
taylor.pensize(15)
taylor.showturtle()
taylor.left(180)
taylor.hideturtle()
taylor.up()
taylor.forward(180)
taylor.showturtle()
taylor.right(90)
taylor.hideturtle()
taylor.forward(180)
taylor.showturtle()
taylor.right(180)
taylor.down()
taylor.hideturtle()
taylor.forward(180)
taylor.showturtle()
taylor.left(180)
taylor.hideturtle()
taylor.forward(90)
taylor.showturtle()
taylor.right(90)
taylor.forward(90)
taylor.left(90)
taylor.hideturtle()
taylor.forward(90)
taylor.left(180)
taylor.forward(180)
taylor.showturtle()
taylor.left(90)
taylor.up()
taylor.hideturtle()
taylor.forward(90)
taylor.showturtle()
taylor.down()
taylor.forward(90)
taylor.left(180)
taylor.forward(45)
taylor.left(90)
taylor.left(180)
taylor.hideturtle()
taylor.forward(180)
taylor.showturtle()
taylor.right(90)
taylor.forward(45)
taylor.left(180)
taylor.forward(90)
taylor.left(180)
taylor.right(90)
taylor.hideturtle()
taylor.up()
taylor.forward(180)
taylor.showturtle()
taylor.hideturtle()
taylor.forward(100)
taylor.right(90)
taylor.left(90)
taylor.forward(100)
taylor.right(90)
taylor.forward(110)
taylor.showturtle()
taylor.hideturtle()
taylor.right(90)
taylor.forward(70)
taylor.showturtle()
taylor.down()
taylor.hideturtle()
taylor.forward(30)
taylor.forward(15)
taylor.forward(5)
taylor.showturtle()
taylor.left(180)
taylor.forward(50)
taylor.right(90)
taylor.right(180)
taylor.forward(50)
taylor.forward(20)
taylor.forward(20)
taylor.forward(20)
taylor.forward(10)
taylor.forward(5)
taylor.left(90)
taylor.forward(50)
taylor.up()
taylor.forward(30)
taylor.hideturtle()
taylor.left(90)
taylor.forward(31.25)
taylor.showturtle()
taylor.right(90)
taylor.hideturtle()
taylor.down()
taylor.forward(50)
taylor.showturtle()
taylor.left(180)
taylor.forward(50)
taylor.right(90)
taylor.hideturtle()
taylor.up()
taylor.forward(31.25)
taylor.hideturtle()
taylor.forward(31.25)
taylor.showturtle()
taylor.right(90)
taylor.hideturtle()
taylor.down()
taylor.showturtle()
taylor.forward(50)
taylor.hideturtle()
